services:
  app:
    image: ghcr.io/quenary/konvoez:1
    container_name: konvoez
    restart: unless-stopped
    ports:
      - '80:80'
      - '40000-40100:40000-40100/udp'
      - '40000-40100:40000-40100/tcp'
    # For high-load Linux production hosts, you can uncomment network_mode: host
    # and comment out the ports section above for maximum WebRTC performance:
    # network_mode: host
    volumes:
      - konvoez_data:/konvoez_data
    environment:
      # See .env.example for more information
      # Secrets (required)
      - MASTER_KEY=${MASTER_KEY:-}
      - JWT_SECRET=${JWT_SECRET:-}
      # Cookies
      - COOKIE_SECURE=${COOKIE_SECURE:-}
      - COOKIE_SAME_SITE=${COOKIE_SAME_SITE:-}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN:-}
      # Mediasoup (required for voice calls)
      # See docs/NETWORKING.md for more information
      - MEDIASOUP_ANNOUNCED_IP=${MEDIASOUP_ANNOUNCED_IP:-}
      - MEDIASOUP_PORT_RANGE=${MEDIASOUP_PORT_RANGE:-}
      # SMTP
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-}
      - SMTP_ENCRYPTION=${SMTP_ENCRYPTION:-}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      - SMTP_FROM=${SMTP_FROM:-}

volumes:
  konvoez_data:
