import { z } from 'zod';

export const SCHEMA_ERROR = {
  REQUIRED: 'VALIDATION.REQUIRED',
  STRING: 'VALIDATION.STRING',
  TTL_RANGE: 'VALIDATION.TTL_RANGE',
  USERNAME_LENGTH: 'VALIDATION.USERNAME_LENGTH',
  PASSWORD_LENGTH: 'VALIDATION.PASSWORD_LENGTH',
  PASSWORD_PATTERN: 'VALIDATION.PASSWORD_PATTERN',
  PASSWORD_MISMATCH: 'VALIDATION.PASSWORD_MISMATCH',
  FULLNAME_LENGTH: 'VALIDATION.FULLNAME_LENGTH',
  EMAIL: 'VALIDATION.EMAIL',
  ROOM_NAME_LENGTH: 'VALIDATION.ROOM_NAME_LENGTH',
  ROOM_TYPE: 'VALIDATION.ROOM_TYPE',
  MESSAGE_LENGTH: 'VALIDATION.MESSAGE_LENGTH',
  SETUP_TOKEN_REQUIRED: 'VALIDATION.SETUP_TOKEN_REQUIRED',
  INVITE_CODE_REQUIRED: 'VALIDATION.INVITE_CODE_REQUIRED',
  INVALID_SCHEMA: 'VALIDATION.INVALID_SCHEMA',
} as const;

export type TSchemaError = (typeof SCHEMA_ERROR)[keyof typeof SCHEMA_ERROR];

export const stringSchema = z.string({ error: SCHEMA_ERROR.STRING });

export const baseEntitySchema = z.object({
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date().nullish(),
});

export type TBaseEntity = z.infer<typeof baseEntitySchema>;
